var searchData = [
  ["Footnotes", "#footnotes"],
  ["Version 1.0", "#version-1.0"],
  ["Changelog", "#changelog"],
  ["Function and Macro and Variable and Type Index", "#function-and-macro-and-variable-and-type-index"],
  ["Concept Index", "#concept-index"],
  ["buffer [second-cluffer.standard-buffer]", "#type-buffer-[second-cluffer.standard-buffer]"],
  ["Class second-cluffer.standard-buffer|buffer", "#*-class-second-cluffer.standard-buffer|buffer"],
  ["right-sticky-cursor [second-cluffer.standard-line]", "#type-right-sticky-cursor-[second-cluffer.standard-line]"],
  ["Class second-cluffer.standard-line|right-sticky-cursor", "#*-class-second-cluffer.standard-line|right-sticky-cursor"],
  ["left-sticky-cursor [second-cluffer.standard-line]", "#type-left-sticky-cursor-[second-cluffer.standard-line]"],
  ["Class second-cluffer.standard-line|left-sticky-cursor", "#*-class-second-cluffer.standard-line|left-sticky-cursor"],
  ["line [second-cluffer.standard-line]", "#type-line-[second-cluffer.standard-line]"],
  ["Class second-cluffer.standard-line|line", "#*-class-second-cluffer.standard-line|line"],
  ["4.2 Standard Implementation", "#4.2-standard-implementation"],
  ["buffer [second-cluffer.simple-buffer]", "#type-buffer-[second-cluffer.simple-buffer]"],
  ["right-sticky-cursor [second-cluffer.simple-line]", "#type-right-sticky-cursor-[second-cluffer.simple-line]"],
  ["left-sticky-cursor [second-cluffer.simple-line]", "#type-left-sticky-cursor-[second-cluffer.simple-line]"],
  ["line [second-cluffer.simple-line]", "#type-line-[second-cluffer.simple-line]"],
  ["Class second-cluffer.simple-line|line", "#*-class-second-cluffer.simple-line|line"],
  ["4.1 Simple Implementation", "#4.1-simple-implementation"],
  ["4 Implementations", "#4-implementations"],
  ["update [second-cluffer.implementation]", "#function-update-[second-cluffer.implementation]"],
  ["3.8 Update Implementation protocol", "#3.8-update-implementation-protocol"],
  ["join-using-buffer [second-cluffer.implementation]", "#function-join-using-buffer-[second-cluffer.implementation]"],
  ["Generic-Function second-cluffer.implementation|join-using-buffer", "#*-generic-function-second-cluffer.implementation|join-using-buffer"],
  ["split-using-buffer [second-cluffer.implementation]", "#function-split-using-buffer-[second-cluffer.implementation]"],
  ["Generic-Function second-cluffer.implementation|split-using-buffer", "#*-generic-function-second-cluffer.implementation|split-using-buffer"],
  ["line-number-using-buffer [second-cluffer.implementation]", "#function-line-number-using-buffer-[second-cluffer.implementation]"],
  ["find-line [second-cluffer.implementation]", "#function-find-line-[second-cluffer.implementation]"],
  ["line-count [second-cluffer.implementation]", "#function-line-count-[second-cluffer.implementation]"],
  ["3.7 Buffer Implementation Protocol", "#3.7-buffer-implementation-protocol"],
  ["note-line-changed [second-cluffer.implementation]", "#function-note-line-changed-[second-cluffer.implementation]"],
  ["3.6 Dock Protocol", "#3.6-dock-protocol"],
  ["make-line-like [second-cluffer.implementation]", "#function-make-line-like-[second-cluffer.implementation]"],
  ["join [second-cluffer.implementation]", "#function-join-[second-cluffer.implementation]"],
  ["Generic-Function second-cluffer.implementation|join", "#*-generic-function-second-cluffer.implementation|join"],
  ["split [second-cluffer.implementation]", "#function-split-[second-cluffer.implementation]"],
  ["Generic-Function second-cluffer.implementation|split", "#*-generic-function-second-cluffer.implementation|split"],
  ["delete-item [second-cluffer.implementation]", "#function-delete-item-[second-cluffer.implementation]"],
  ["Generic-Function second-cluffer.implementation|delete-item", "#*-generic-function-second-cluffer.implementation|delete-item"],
  ["insert-item [second-cluffer.implementation]", "#function-insert-item-[second-cluffer.implementation]"],
  ["Generic-Function second-cluffer.implementation|insert-item", "#*-generic-function-second-cluffer.implementation|insert-item"],
  ["item [second-cluffer.implementation]", "#function-item-[second-cluffer.implementation]"],
  ["Generic-Function second-cluffer.implementation|item", "#*-generic-function-second-cluffer.implementation|item"],
  ["last-line-p [second-cluffer.implementation]", "#function-last-line-p-[second-cluffer.implementation]"],
  ["first-line-p [second-cluffer.implementation]", "#function-first-line-p-[second-cluffer.implementation]"],
  ["(setf dock) [second-cluffer.implementation]", "#function-(setf-dock)-[second-cluffer.implementation]"],
  ["dock [second-cluffer.implementation]", "#function-dock-[second-cluffer.implementation]"],
  ["3.5 Line Implementation Protocol", "#3.5-line-implementation-protocol"],
  ["delete-item-after [second-cluffer.implementation]", "#function-delete-item-after-[second-cluffer.implementation]"],
  ["Generic-Function second-cluffer.implementation|delete-item-after", "#*-generic-function-second-cluffer.implementation|delete-item-after"],
  ["delete-item-before [second-cluffer.implementation]", "#function-delete-item-before-[second-cluffer.implementation]"],
  ["Generic-Function second-cluffer.implementation|delete-item-before", "#*-generic-function-second-cluffer.implementation|delete-item-before"],
  ["insert-item-at [second-cluffer.implementation]", "#function-insert-item-at-[second-cluffer.implementation]"],
  ["item-after [second-cluffer.implementation]", "#function-item-after-[second-cluffer.implementation]"],
  ["Generic-Function second-cluffer.implementation|item-after", "#*-generic-function-second-cluffer.implementation|item-after"],
  ["item-before [second-cluffer.implementation]", "#function-item-before-[second-cluffer.implementation]"],
  ["Generic-Function second-cluffer.implementation|item-before", "#*-generic-function-second-cluffer.implementation|item-before"],
  ["3.4.4 Cursor Items", "#3.4.4-cursor-items"],
  ["end-of-line [second-cluffer.implementation]", "#function-end-of-line-[second-cluffer.implementation]"],
  ["beginning-of-line [second-cluffer.implementation]", "#function-beginning-of-line-[second-cluffer.implementation]"],
  ["forward-item [second-cluffer.implementation]", "#function-forward-item-[second-cluffer.implementation]"],
  ["backward-item [second-cluffer.implementation]", "#function-backward-item-[second-cluffer.implementation]"],
  ["3.4.3 Cursor Movement", "#3.4.3-cursor-movement"],
  ["end-of-buffer-p [second-cluffer.implementation]", "#function-end-of-buffer-p-[second-cluffer.implementation]"],
  ["beginning-of-buffer-p [second-cluffer.implementation]", "#function-beginning-of-buffer-p-[second-cluffer.implementation]"],
  ["end-of-line-p [second-cluffer.implementation]", "#function-end-of-line-p-[second-cluffer.implementation]"],
  ["beginning-of-line-p [second-cluffer.implementation]", "#function-beginning-of-line-p-[second-cluffer.implementation]"],
  ["(setf index) [second-cluffer.implementation]", "#function-(setf-index)-[second-cluffer.implementation]"],
  ["index [second-cluffer.implementation]", "#function-index-[second-cluffer.implementation]"],
  ["Generic-Function second-cluffer.implementation|index", "#*-generic-function-second-cluffer.implementation|index"],
  ["3.4.2 Cursor Location", "#3.4.2-cursor-location"],
  ["detach [second-cluffer.implementation]", "#function-detach-[second-cluffer.implementation]"],
  ["Generic-Function second-cluffer.implementation|detach", "#*-generic-function-second-cluffer.implementation|detach"],
  ["attach [second-cluffer.implementation]", "#function-attach-[second-cluffer.implementation]"],
  ["Generic-Function second-cluffer.implementation|attach", "#*-generic-function-second-cluffer.implementation|attach"],
  ["3.4.1 Cursor Attachment", "#3.4.1-cursor-attachment"],
  ["stickiness [second-cluffer]", "#function-stickiness-[second-cluffer]"],
  ["stickiness", "#concept-stickiness"],
  ["stickiness", "#concept-stickiness-12"],
  ["3.4 Cursor Implementation Protocol", "#3.4-cursor-implementation-protocol"],
  ["line-number [second-cluffer.implementation]", "#function-line-number-[second-cluffer.implementation]"],
  ["3.3 Line Number Implementation Protocol", "#3.3-line-number-implementation-protocol"],
  ["items [second-cluffer.implementation]", "#function-items-[second-cluffer.implementation]"],
  ["item-count [second-cluffer.implementation]", "#function-item-count-[second-cluffer.implementation]"],
  ["Generic-Function second-cluffer.implementation|item-count", "#*-generic-function-second-cluffer.implementation|item-count"],
  ["3.2 Item Container Implementation Protocol", "#3.2-item-container-implementation-protocol"],
  ["location= [second-cluffer.implementation]", "#function-location=-[second-cluffer.implementation]"],
  ["Generic-Function second-cluffer.implementation|location=", "#*-generic-function-second-cluffer.implementation|location="],
  ["location<= [second-cluffer.implementation]", "#function-location<=-[second-cluffer.implementation]"],
  ["Generic-Function second-cluffer.implementation|location<=", "#*-generic-function-second-cluffer.implementation|location<="],
  ["location< [second-cluffer.implementation]", "#function-location<-[second-cluffer.implementation]"],
  ["Generic-Function second-cluffer.implementation|location<", "#*-generic-function-second-cluffer.implementation|location<"],
  ["3.1 Location Comparison Implementation Protocol", "#3.1-location-comparison-implementation-protocol"],
  ["3 Implementation Protocols", "#3-implementation-protocols"],
  ["make-empty-buffer [second-cluffer]", "#function-make-empty-buffer-[second-cluffer]"],
  ["Function second-cluffer|make-empty-buffer", "#*-function-second-cluffer|make-empty-buffer"],
  ["2.13 Convenience Functions", "#2.13-convenience-functions"],
  ["update [second-cluffer]", "#function-update-[second-cluffer]"],
  ["Generic-Function second-cluffer|update", "#*-generic-function-second-cluffer|update"],
  ["time stamp", "#concept-time-stamp"],
  ["2.12 Update Protocol", "#2.12-update-protocol"],
  ["find-line [second-cluffer]", "#function-find-line-[second-cluffer]"],
  ["Generic-Function second-cluffer|find-line", "#*-generic-function-second-cluffer|find-line"],
  ["line-count [second-cluffer]", "#function-line-count-[second-cluffer]"],
  ["2.11 Buffer Protocol", "#2.11-buffer-protocol"],
  ["join [second-cluffer]", "#function-join-[second-cluffer]"],
  ["Generic-Function second-cluffer|join", "#*-generic-function-second-cluffer|join"],
  ["split [second-cluffer]", "#function-split-[second-cluffer]"],
  ["Generic-Function second-cluffer|split", "#*-generic-function-second-cluffer|split"],
  ["delete-item [second-cluffer]", "#function-delete-item-[second-cluffer]"],
  ["Generic-Function second-cluffer|delete-item", "#*-generic-function-second-cluffer|delete-item"],
  ["right-sticky", "#concept-right-sticky"],
  ["right-sticky", "#concept-right-sticky-7"],
  ["right-sticky", "#concept-right-sticky-8"],
  ["right-sticky", "#concept-right-sticky-9"],
  ["right-sticky", "#concept-right-sticky-10"],
  ["right-sticky", "#concept-right-sticky-11"],
  ["left-sticky", "#concept-left-sticky"],
  ["left-sticky", "#concept-left-sticky-2"],
  ["left-sticky", "#concept-left-sticky-3"],
  ["left-sticky", "#concept-left-sticky-4"],
  ["left-sticky", "#concept-left-sticky-5"],
  ["left-sticky", "#concept-left-sticky-6"],
  ["insert-item [second-cluffer]", "#function-insert-item-[second-cluffer]"],
  ["Generic-Function second-cluffer|insert-item", "#*-generic-function-second-cluffer|insert-item"],
  ["item [second-cluffer]", "#function-item-[second-cluffer]"],
  ["Generic-Function second-cluffer|item", "#*-generic-function-second-cluffer|item"],
  ["last-line-p [second-cluffer]", "#function-last-line-p-[second-cluffer]"],
  ["first-line-p [second-cluffer]", "#function-first-line-p-[second-cluffer]"],
  ["2.10 Line Protocol", "#2.10-line-protocol"],
  ["join-line [second-cluffer]", "#function-join-line-[second-cluffer]"],
  ["Generic-Function second-cluffer|join-line", "#*-generic-function-second-cluffer|join-line"],
  ["split-line [second-cluffer]", "#function-split-line-[second-cluffer]"],
  ["delete-item-after [second-cluffer]", "#function-delete-item-after-[second-cluffer]"],
  ["delete-item-before [second-cluffer]", "#function-delete-item-before-[second-cluffer]"],
  ["insert-item-at [second-cluffer]", "#function-insert-item-at-[second-cluffer]"],
  ["item-after [second-cluffer]", "#function-item-after-[second-cluffer]"],
  ["item-before [second-cluffer]", "#function-item-before-[second-cluffer]"],
  ["2.9.4 Cursor Items", "#2.9.4-cursor-items"],
  ["end-of-line [second-cluffer]", "#function-end-of-line-[second-cluffer]"],
  ["beginning-of-line [second-cluffer]", "#function-beginning-of-line-[second-cluffer]"],
  ["backward-item [second-cluffer]", "#function-backward-item-[second-cluffer]"],
  ["forward-item [second-cluffer]", "#function-forward-item-[second-cluffer]"],
  ["2.9.3 Cursor Movement", "#2.9.3-cursor-movement"],
  ["end-of-buffer-p [second-cluffer]", "#function-end-of-buffer-p-[second-cluffer]"],
  ["beginning-of-buffer-p [second-cluffer]", "#function-beginning-of-buffer-p-[second-cluffer]"],
  ["end-of-line-p [second-cluffer]", "#function-end-of-line-p-[second-cluffer]"],
  ["beginning-of-line-p [second-cluffer]", "#function-beginning-of-line-p-[second-cluffer]"],
  ["(setf index) [second-cluffer]", "#function-(setf-index)-[second-cluffer]"],
  ["Generic-Function second-cluffer|(setf index)", "#*-generic-function-second-cluffer|(setf-index)"],
  ["index [second-cluffer]", "#function-index-[second-cluffer]"],
  ["Generic-Function second-cluffer|index", "#*-generic-function-second-cluffer|index"],
  ["2.9.2 Cursor Location", "#2.9.2-cursor-location"],
  ["detach [second-cluffer]", "#function-detach-[second-cluffer]"],
  ["attach [second-cluffer]", "#function-attach-[second-cluffer]"],
  ["attachedp [second-cluffer]", "#function-attachedp-[second-cluffer]"],
  ["2.9.1 Cursor Attachment", "#2.9.1-cursor-attachment"],
  ["2.9 Cursor Protocol", "#2.9-cursor-protocol"],
  ["2.8 Buffer Link Protocol", "#2.8-buffer-link-protocol"],
  ["Generic-Function second-cluffer|line", "#*-generic-function-second-cluffer|line"],
  ["2.7 Line Link Protocol", "#2.7-line-link-protocol"],
  ["line-number [second-cluffer]", "#function-line-number-[second-cluffer]"],
  ["2.6 Line Number Protocol", "#2.6-line-number-protocol"],
  ["items [second-cluffer]", "#function-items-[second-cluffer]"],
  ["item-count [second-cluffer]", "#function-item-count-[second-cluffer]"],
  ["Generic-Function second-cluffer|item-count", "#*-generic-function-second-cluffer|item-count"],
  ["2.5 Item Container Protocol", "#2.5-item-container-protocol"],
  ["location> [second-cluffer]", "#function-location>-[second-cluffer]"],
  ["location>= [second-cluffer]", "#function-location>=-[second-cluffer]"],
  ["location/= [second-cluffer]", "#function-location/=-[second-cluffer]"],
  ["location= [second-cluffer]", "#function-location=-[second-cluffer]"],
  ["location<= [second-cluffer]", "#function-location<=-[second-cluffer]"],
  ["location< [second-cluffer]", "#function-location<-[second-cluffer]"],
  ["2.4 Location Comparison Protocol", "#2.4-location-comparison-protocol"],
  ["buffer [second-cluffer]", "#type-buffer-[second-cluffer]"],
  ["buffer [second-cluffer]", "#function-buffer-[second-cluffer]"],
  ["Class second-cluffer|buffer", "#*-class-second-cluffer|buffer"],
  ["cursor [second-cluffer]", "#type-cursor-[second-cluffer]"],
  ["Class second-cluffer|cursor", "#*-class-second-cluffer|cursor"],
  ["line [second-cluffer]", "#type-line-[second-cluffer]"],
  ["line [second-cluffer]", "#function-line-[second-cluffer]"],
  ["Class second-cluffer|line", "#*-class-second-cluffer|line"],
  ["2.3 Protocol Classes", "#2.3-protocol-classes"],
  ["line-detached-error [second-cluffer]", "#type-line-detached-error-[second-cluffer]"],
  ["Class second-cluffer|line-detached-error", "#*-class-second-cluffer|line-detached-error"],
  ["end-of-buffer-error [second-cluffer]", "#type-end-of-buffer-error-[second-cluffer]"],
  ["Class second-cluffer|end-of-buffer-error", "#*-class-second-cluffer|end-of-buffer-error"],
  ["beginning-of-buffer-error [second-cluffer]", "#type-beginning-of-buffer-error-[second-cluffer]"],
  ["Class second-cluffer|beginning-of-buffer-error", "#*-class-second-cluffer|beginning-of-buffer-error"],
  ["end-of-line-error [second-cluffer]", "#type-end-of-line-error-[second-cluffer]"],
  ["Class second-cluffer|end-of-line-error", "#*-class-second-cluffer|end-of-line-error"],
  ["beginning-of-line-error [second-cluffer]", "#type-beginning-of-line-error-[second-cluffer]"],
  ["Class second-cluffer|beginning-of-line-error", "#*-class-second-cluffer|beginning-of-line-error"],
  ["cursors-not-comparable-error [second-cluffer]", "#type-cursors-not-comparable-error-[second-cluffer]"],
  ["Class second-cluffer|cursors-not-comparable-error", "#*-class-second-cluffer|cursors-not-comparable-error"],
  ["cursor-detached-error [second-cluffer]", "#type-cursor-detached-error-[second-cluffer]"],
  ["Class second-cluffer|cursor-detached-error", "#*-class-second-cluffer|cursor-detached-error"],
  ["cursor-attached-error [second-cluffer]", "#type-cursor-attached-error-[second-cluffer]"],
  ["Class second-cluffer|cursor-attached-error", "#*-class-second-cluffer|cursor-attached-error"],
  ["cluffer-error [second-cluffer]", "#type-cluffer-error-[second-cluffer]"],
  ["2.2 Conditions", "#2.2-conditions"],
  ["2.1 Packages", "#2.1-packages"],
  ["2 External Protocols", "#2-external-protocols"],
  ["1 Introduction", "#1-introduction"]
];
