var searchData = [
  ["Function Index", "#function-index"],
  ["Concept Index", "#concept-index"],
  ["Footnotes", "#footnotes"],
  ["Function and macro and variable and type index", "#function-and-macro-and-variable-and-type-index"],
  ["Concept index", "#concept-index"],
  ["7.2 Development History", "#7.2-development-history"],
  ["Visible area", "#function-visible-area"],
  ["User transformation", "#function-user-transformation"],
  ["User coordinates", "#function-user-coordinates"],
  ["User clipping region", "#function-user-clipping-region"],
  ["Clipping region", "#function-clipping-region"],
  ["Sheet transformation", "#function-sheet-transformation"],
  ["Sheet region", "#function-sheet-region"],
  ["Sheet coordinates", "#function-sheet-coordinates"],
  ["Potentially visible area", "#function-potentially-visible-area"],
  ["Native transformation", "#function-native-transformation"],
  ["Native region", "#function-native-region"],
  ["Native coordinates", "#function-native-coordinates"],
  ["Mirror transformation", "#function-mirror-transformation"],
  ["Mirrored sheet", "#function-mirrored-sheet"],
  ["Mirror", "#function-mirror"],
  ["Medium transformation", "#function-medium-transformation"],
  ["Medium", "#function-medium"],
  ["Direct mirror", "#function-direct-mirror"],
  ["Device transformation", "#function-device-transformation"],
  ["Armed gadget", "#function-armed-gadget"],
  ["Active gadget", "#function-active-gadget"],
  ["7.1 Glossary", "#7.1-glossary"],
  ["Auxiliary material", "#auxiliary-material"],
  ["6.3.5 Debugger integration", "#6.3.5-debugger-integration"],
  ["6.3.4 Command output destinations", "#6.3.4-command-output-destinations"],
  ["6.3.3 Calling commands from lisp", "#6.3.3-calling-commands-from-lisp"],
  ["6.3.2 The #! macro character", "#6.3.2-the-#!-macro-character"],
  ["6.3.1.2 Commands", "#6.3.1.2-commands"],
  ["6.3.1.1 Quick start", "#6.3.1.1-quick-start"],
  ["6.3.1 Usage", "#6.3.1-usage"],
  ["Listener", "#concept-listener"],
  ["CLIM Listener", "#concept-clim-listener"],
  ["Lisp Listener", "#concept-lisp-listener"],
  ["6.3 Listener", "#6.3-listener"],
  ["6.2.3.4 Deprecated Functions", "#6.2.3.4-deprecated-functions"],
  ["Generic-Function clouseau:inspect-object", "#function-generic-function-clouseau:inspect-object"],
  ["Generic-Function clouseau:inspect-place", "#function-generic-function-clouseau:inspect-place"],
  ["6.2.3.3 Other Functions", "#6.2.3.3-other-functions"],
  ["Function clouseau:format-place-row", "#function-function-clouseau:format-place-row"],
  ["Function clouseau:format-place-cells", "#function-function-clouseau:format-place-cells"],
  ["Macro clouseau:formatting-place", "#function-macro-clouseau:formatting-place"],
  ["Macro clouseau:without-noting-object-occurrences", "#function-macro-clouseau:without-noting-object-occurrences"],
  ["Macro clouseau:call-without-noting-object-occurrences", "#function-macro-clouseau:call-without-noting-object-occurrences"],
  ["Generic-Function clouseau:note-object-occurrence", "#function-generic-function-clouseau:note-object-occurrence"],
  ["Generic-Function clouseau:inspect-object-using-state", "#function-generic-function-clouseau:inspect-object-using-state"],
  ["6.2.3.2 Functions for Extending Clouseau", "#6.2.3.2-functions-for-extending-clouseau"],
  ["Function clouseau:inspect", "#function-function-clouseau:inspect"],
  ["6.2.3.1 Functions for Invoking Clouseau", "#6.2.3.1-functions-for-invoking-clouseau"],
  ["6.2.3 API", "#6.2.3-api"],
  ["6.2.2.3 Defining Inspection Methods for Objects", "#6.2.2.3-defining-inspection-methods-for-objects"],
  ["5-definition", "#footnote-5-definition"],
  ["5-reference", "#footnote-5-reference"],
  ["6.2.2.2 State and Style of Presented Objects", "#6.2.2.2-state-and-style-of-presented-objects"],
  ["6.2.2.1 Running Example", "#6.2.2.1-running-example"],
  ["6.2.2 Extending Clouseau", "#6.2.2-extending-clouseau"],
  ["6.2.1.7 Updating the Inspected Object", "#6.2.1.7-updating-the-inspected-object"],
  ["4-definition", "#footnote-4-definition"],
  ["4-reference", "#footnote-4-reference"],
  ["6.2.1.6 Handling of Specific Object Types", "#6.2.1.6-handling-of-specific-object-types"],
  ["6.2.1.5 Navigating", "#6.2.1.5-navigating"],
  ["6.2.1.4 Evaluating Forms", "#6.2.1.4-evaluating-forms"],
  ["6.2.1.3 Objects and Places", "#6.2.1.3-objects-and-places"],
  ["6.2.1.2 The Inspector Window", "#6.2.1.2-the-inspector-window"],
  ["6.2.1.1 Quick Start", "#6.2.1.1-quick-start"],
  ["6.2.1 Usage", "#6.2.1-usage"],
  ["Clouseau", "#concept-clouseau"],
  ["inspector", "#concept-inspector"],
  ["6.2 Inspector", "#6.2-inspector"],
  ["6.1.3 API", "#6.1.3-api"],
  ["6.1.2 Keyboard shortcuts", "#6.1.2-keyboard-shortcuts"],
  ["6.1.1 Usage", "#6.1.1-usage"],
  ["Debugger", "#concept-debugger"],
  ["CLIM Debugger", "#concept-clim-debugger"],
  ["Lisp Debugger", "#concept-lisp-debugger"],
  ["6.1 Debugger", "#6.1-debugger"],
  ["6 Applications", "#6-applications"],
  ["5.10 Additional arguments to drawing functions", "#5.10-additional-arguments-to-drawing-functions"],
  ["3-definition", "#footnote-3-definition"],
  ["3-reference", "#footnote-3-reference"],
  ["5.9 Updating frame instances after frame class redefinition", "#5.9-updating-frame-instances-after-frame-class-redefinition"],
  ["Macro clime:with-output-to-rgba-pattern", "#function-macro-clime:with-output-to-rgba-pattern"],
  ["Macro clime:with-output-to-image-stream", "#function-macro-clime:with-output-to-image-stream"],
  ["5.8.1 Raster image as a medium", "#5.8.1-raster-image-as-a-medium"],
  ["5.8 Raster Images", "#5.8-raster-images"],
  ["Generic-Function clim-extensions:font-face-text-style", "#function-generic-function-clim-extensions:font-face-text-style"],
  ["Generic-Function clim-extensions:font-face-all-sizes", "#function-generic-function-clim-extensions:font-face-all-sizes"],
  ["Generic-Function clim-extensions:font-face-family", "#function-generic-function-clim-extensions:font-face-family"],
  ["Generic-Function clim-extensions:font-face-name", "#function-generic-function-clim-extensions:font-face-name"],
  ["Generic-Function clim-extensions:font-family-all-faces", "#function-generic-function-clim-extensions:font-family-all-faces"],
  ["Generic-Function clim-extensions:font-family-port", "#function-generic-function-clim-extensions:font-family-port"],
  ["Generic-Function clim-extensions:font-family-name", "#function-generic-function-clim-extensions:font-family-name"],
  ["Generic-Function clim-extensions:port-all-font-families", "#function-generic-function-clim-extensions:port-all-font-families"],
  ["Class clim-extensions:font-face", "#function-class-clim-extensions:font-face"],
  ["Class clim-extensions:font-family", "#function-class-clim-extensions:font-family"],
  ["5.7.2 Listing Fonts", "#5.7.2-listing-fonts"],
  ["5.7.1 Extended Text Styles", "#5.7.1-extended-text-styles"],
  ["5.7 Fonts and Extended Text Styles", "#5.7-fonts-and-extended-text-styles"],
  ["Generic-Function clim-tab-layout:note-tab-page-changed", "#function-generic-function-clim-tab-layout:note-tab-page-changed"],
  ["Function clim-tab-layout:remove-page-named", "#function-function-clim-tab-layout:remove-page-named"],
  ["Function clim-tab-layout:switch-to-page", "#function-function-clim-tab-layout:switch-to-page"],
  ["Function clim-tab-layout:find-tab-page-named", "#function-function-clim-tab-layout:find-tab-page-named"],
  ["Function clim-tab-layout:sheet-to-page", "#function-function-clim-tab-layout:sheet-to-page"],
  ["Generic-Function clim-tab-layout:tab-layout-enabled-page", "#function-generic-function-clim-tab-layout:tab-layout-enabled-page"],
  ["Function clim-tab-layout:remove-page", "#function-function-clim-tab-layout:remove-page"],
  ["Function clim-tab-layout:add-page", "#function-function-clim-tab-layout:add-page"],
  ["Generic-Function clim-tab-layout:tab-page-drawing-options", "#function-generic-function-clim-tab-layout:tab-page-drawing-options"],
  ["Generic-Function clim-tab-layout:tab-page-presentation-type", "#function-generic-function-clim-tab-layout:tab-page-presentation-type"],
  ["Generic-Function clim-tab-layout:tab-page-pane", "#function-generic-function-clim-tab-layout:tab-page-pane"],
  ["Generic-Function clim-tab-layout:tab-page-title", "#function-generic-function-clim-tab-layout:tab-page-title"],
  ["Generic-Function clim-tab-layout:tab-page-tab-layout", "#function-generic-function-clim-tab-layout:tab-page-tab-layout"],
  ["Generic-Function clim-tab-layout:tab-layout-pages", "#function-generic-function-clim-tab-layout:tab-layout-pages"],
  ["Macro clim-tab-layout:with-tab-layout", "#function-macro-clim-tab-layout:with-tab-layout"],
  ["Class clim-tab-layout:tab-page", "#function-class-clim-tab-layout:tab-page"],
  ["Class clim-tab-layout:tab-layout-pane", "#function-class-clim-tab-layout:tab-layout-pane"],
  ["Class clim-tab-layout:tab-layout", "#function-class-clim-tab-layout:tab-layout"],
  ["5.6 Tab Layout", "#5.6-tab-layout"],
  ["blank area", "#concept-blank-area"],
  ["5.5 Extended blank area presentation type", "#5.5-extended-blank-area-presentation-type"],
  ["5.4.1.1 FILLING-OUTPUT extension", "#5.4.1.1-filling-output-extension"],
  ["Macro clime:with-temporary-margins", "#function-macro-clime:with-temporary-margins"],
  ["Function clime:stream-page-region", "#function-function-clime:stream-page-region"],
  ["Function clime:page-final-position", "#function-function-clime:page-final-position"],
  ["Function clime:page-initial-position", "#function-function-clime:page-initial-position"],
  ["5.4.1 Page abstraction", "#5.4.1-page-abstraction"],
  ["5.4 Extended text formatting", "#5.4-extended-text-formatting"],
  ["text-field", "#concept-text-field"],
  ["text-editor", "#concept-text-editor"],
  ["input-editor", "#concept-input-editor"],
  ["drei", "#concept-drei"],
  ["5.3 Text editor substrate", "#5.3-text-editor-substrate"],
  ["Generic-Function clim-extensions:note-frame-pretty-name-changed", "#function-generic-function-clim-extensions:note-frame-pretty-name-changed"],
  ["Generic-Function clim-extensions:setf-sheet-pretty-name", "#function-generic-function-clim-extensions:setf-sheet-pretty-name"],
  ["Generic-Function clim-extensions:sheet-pretty-name", "#function-generic-function-clim-extensions:sheet-pretty-name"],
  ["Generic-Function clim-extensions:sheet-name", "#function-generic-function-clim-extensions:sheet-name"],
  ["5.2 Frame and sheet names", "#5.2-frame-and-sheet-names"],
  ["Generic-Function clim-extensions:note-frame-icon-changed", "#function-generic-function-clim-extensions:note-frame-icon-changed"],
  ["Generic-Function clim-extensions:setf-frame-icon", "#function-generic-function-clim-extensions:setf-frame-icon"],
  ["Generic-Function clim-extensions:frame-icon", "#function-generic-function-clim-extensions:frame-icon"],
  ["Generic-Function clim-extensions:setf-sheet-icon", "#function-generic-function-clim-extensions:setf-sheet-icon"],
  ["Generic-Function clim-extensions:sheet-icon", "#function-generic-function-clim-extensions:sheet-icon"],
  ["5.1 Frame and sheet icons", "#5.1-frame-and-sheet-icons"],
  ["5 Extensions", "#5-extensions"],
  ["4.3.2 Additional functions", "#4.3.2-additional-functions"],
  ["4.3.1 Postscript fonts", "#4.3.1-postscript-fonts"],
  ["4.3 PostScript backend", "#4.3-postscript-backend"],
  ["4.2.13 Obsolete", "#4.2.13-obsolete"],
  ["4.2.12 Miscellaneous", "#4.2.12-miscellaneous"],
  ["Function clim-backend:register-output-destination-type", "#function-function-clim-backend:register-output-destination-type"],
  ["Generic-Function clim-backend:invoke-with-standard-output", "#function-generic-function-clim-backend:invoke-with-standard-output"],
  ["4.2.11 Additional output destinations", "#4.2.11-additional-output-destinations"],
  ["4.2.10 Text size", "#4.2.10-text-size"],
  ["4.2.9 Pointer protocol (events?)", "#4.2.9-pointer-protocol-(events?)"],
  ["4.2.8 Frame manager, panes and gadgets", "#4.2.8-frame-manager,-panes-and-gadgets"],
  ["4.2.7 Port protocol", "#4.2.7-port-protocol"],
  ["4.2.6 Medium operation", "#4.2.6-medium-operation"],
  ["4.2.5 Medium drawing", "#4.2.5-medium-drawing"],
  ["4.2.4 Graft protocol", "#4.2.4-graft-protocol"],
  ["4.2.3 Event handling", "#4.2.3-event-handling"],
  ["4.2.2 Backend protocol", "#4.2.2-backend-protocol"],
  ["4.2.1 Different types of backends", "#4.2.1-different-types-of-backends"],
  ["4.2 Writing backends", "#4.2-writing-backends"],
  ["4.1.1.1 Examples", "#4.1.1.1-examples"],
  ["4.1.1 Packages", "#4.1.1-packages"],
  ["4.1 Coding conventions", "#4.1-coding-conventions"],
  ["4 Developer manual", "#4-developer-manual"],
  ["2-definition", "#footnote-2-definition"],
  ["2-reference", "#footnote-2-reference"],
  ["3.7 Incremental redisplay", "#3.7-incremental-redisplay"],
  ["3.6 Command Processing", "#3.6-command-processing"],
  ["Macro clim:with-output-to-output-record", "#function-macro-clim:with-output-to-output-record"],
  ["Macro clim:with-new-output-record", "#function-macro-clim:with-new-output-record"],
  ["Generic-Function clim:invoke-with-new-output-record", "#function-generic-function-clim:invoke-with-new-output-record"],
  ["Generic-Function clim:clear-output-record", "#function-generic-function-clim:clear-output-record"],
  ["Generic-Function clim:delete-output-record", "#function-generic-function-clim:delete-output-record"],
  ["Generic-Function clim:add-output-record", "#function-generic-function-clim:add-output-record"],
  ["Class clim:standard-output-recording-stream", "#function-class-clim:standard-output-recording-stream"],
  ["Generic-Function clim:map-over-output-records-overlapping-region", "#function-generic-function-clim:map-over-output-records-overlapping-region"],
  ["Generic-Function clim:map-over-output-records-containing-position", "#function-generic-function-clim:map-over-output-records-containing-position"],
  ["Function clim:map-over-output-records", "#function-function-clim:map-over-output-records"],
  ["Generic-Function clim:replay-output-record", "#function-generic-function-clim:replay-output-record"],
  ["Generic-Function (setf clim:output-record-parent)", "#function-generic-function-(setf-clim:output-record-parent)"],
  ["Generic-Function clim-extensions:line-style-effective-dashes", "#function-generic-function-clim-extensions:line-style-effective-dashes"],
  ["Generic-Function clim-extensions:line-style-effective-thickness", "#function-generic-function-clim-extensions:line-style-effective-thickness"],
  ["Generic-Function clim-extensions:medium-miter-limit", "#function-generic-function-clim-extensions:medium-miter-limit"],
  ["3.5 Output Protocol", "#3.5-output-protocol"],
  ["3.4.4.3 Change-space Notification Protocol", "#3.4.4.3-change-space-notification-protocol"],
  ["space-allocation", "#function-space-allocation"],
  ["3.4.4.2 Space allocation", "#3.4.4.2-space-allocation"],
  ["3.4.4.1 Space composition", "#3.4.4.1-space-composition"],
  ["layout protocol", "#concept-layout-protocol"],
  ["3.4.4 Layout protocol", "#3.4.4-layout-protocol"],
  ["Generic-Function clim:redisplay-frame-panes", "#function-generic-function-clim:redisplay-frame-panes"],
  ["Generic-Function clim:redisplay-frame-pane", "#function-generic-function-clim:redisplay-frame-pane"],
  ["redisplaying panes", "#concept-redisplaying-panes"],
  ["3.4.3 Redisplaying panes", "#3.4.3-redisplaying-panes"],
  ["3.4.2 Pane names", "#3.4.2-pane-names"],
  ["Panes order", "#concept-panes-order"],
  ["1-definition", "#footnote-1-definition"],
  ["1-reference", "#footnote-1-reference"],
  ["@code{make-pane} and @code{:scroll-bars} obsolescence", "#concept-@code{make-pane}-and-@code{:scroll-bars}-obsolescence"],
  ["3.4.1 Creating panes", "#3.4.1-creating-panes"],
  ["3.4 Panes", "#3.4-panes"],
  ["3.3.2 CLIM drawing", "#3.3.2-clim-drawing"],
  ["3.3.1 Windowing system drawing", "#3.3.1-windowing-system-drawing"],
  ["3.3 Drawing functions", "#3.3-drawing-functions"],
  ["3.2.4 Scrolling", "#3.2.4-scrolling"],
  ["3.2.3 Moving and resizing sheets and regions", "#3.2.3-moving-and-resizing-sheets-and-regions"],
  ["3.2.2 Computing the native region", "#3.2.2-computing-the-native-region"],
  ["3.2.1 Computing the native transformation", "#3.2.1-computing-the-native-transformation"],
  ["3.2 Sheet hierarchies", "#3.2-sheet-hierarchies"],
  ["3.1.2 Arguments to drawing functions", "#3.1.2-arguments-to-drawing-functions"],
  ["sheet coordinates", "#concept-sheet-coordinates"],
  ["sheet coordinate system", "#concept-sheet-coordinate-system"],
  ["user coordinates", "#concept-user-coordinates"],
  ["user coordinate system", "#concept-user-coordinate-system"],
  ["3.1.1 Coordinate systems", "#3.1.1-coordinate-systems"],
  ["3.1 Concepts", "#3.1-concepts"],
  ["3 Reference manual", "#3-reference-manual"],
  ["Function clim:remove-menu-item-from-command-table", "#function-function-clim:remove-menu-item-from-command-table"],
  ["Function clim:add-menu-item-to-command-table", "#function-function-clim:add-menu-item-to-command-table"],
  ["2.7.2 Modifying Menu bar", "#2.7.2-modifying-menu-bar"],
  ["Adding sub-menu to menu bar", "#concept-adding-sub-menu-to-menu-bar"],
  ["2.7.1 Creating Menu bar", "#2.7.1-creating-menu-bar"],
  ["menu bar", "#concept-menu-bar"],
  ["2.7 Using menu bar", "#2.7-using-menu-bar"],
  ["command tables", "#concept-command-tables"],
  ["command processing", "#concept-command-processing"],
  ["command table", "#concept-command-table"],
  ["2.6 Using command tables", "#2.6-using-command-tables"],
  ["view", "#concept-view"],
  ["2.5 Using views", "#2.5-using-views"],
  ["2.4.2 A simple example", "#2.4.2-a-simple-example"],
  ["2.4.1 What is a presentation type", "#2.4.1-what-is-a-presentation-type"],
  ["presentation type", "#concept-presentation-type"],
  ["2.4 Using presentation types", "#2.4-using-presentation-types"],
  ["incremental redisplay", "#concept-incremental-redisplay"],
  ["2.3 Using incremental redisplay", "#2.3-using-incremental-redisplay"],
  ["display function", "#concept-display-function"],
  ["2.2.8 An application displaying a data structure", "#2.2.8-an-application-displaying-a-data-structure"],
  ["output recording", "#concept-output-recording"],
  ["command", "#concept-command"],
  ["2.2.7 Adding Functionality", "#2.2.7-adding-functionality"],
  ["2.2.6 Executing the Application", "#2.2.6-executing-the-application"],
  ["2.2.5 A First Attempt", "#2.2.5-a-first-attempt"],
  ["application frame", "#concept-application-frame"],
  ["2.2.4 Defining Application Frames", "#2.2.4-defining-application-frames"],
  ["gadget", "#concept-gadget"],
  ["pane", "#concept-pane"],
  ["2.2.3 Panes and Gadgets", "#2.2.3-panes-and-gadgets"],
  ["2.2.2 How CLIM applications produce output", "#2.2.2-how-clim-applications-produce-output"],
  ["2.2.1 A bit of terminology", "#2.2.1-a-bit-of-terminology"],
  ["writing an application", "#concept-writing-an-application"],
  ["building an application", "#concept-building-an-application"],
  ["2.2 The first application", "#2.2-the-first-application"],
  ["2.1.1.1 Applications", "#2.1.1.1-applications"],
  ["2.1.1 Examples and demos", "#2.1.1-examples-and-demos"],
  ["2.1 Building McCLIM", "#2.1-building-mcclim"],
  ["2 User manual", "#2-user-manual"],
  ["command loop", "#concept-command-loop"],
  ["event loop", "#concept-event-loop"],
  ["interface manager", "#concept-interface-manager"],
  ["2.2 How CLIM Is Different", "#2.2-how-clim-is-different"],
  ["specification", "#concept-specification"],
  ["2.1 Standards", "#2.1-standards"],
  ["Introduction", "#introduction"],
  ["1 McCLIM User's Manual", "#1-mcclim-user's-manual"],
  ["Table of Contents", "#table-of-contents"]
  ];
