var searchData = [
  ["Details", "#details"],
  ["Project trucler", "#project-trucler"],
  ["Project tazivor", "#project-tazivor"],
  ["Project salmagundi", "#project-salmagundi"],
  ["Project s-expression-syntax", "#project-s-expression-syntax"],
  ["Project quaviver", "#project-quaviver"],
  ["Project parcl", "#project-parcl"],
  ["Project maclina", "#project-maclina"],
  ["Project khazern", "#project-khazern"],
  ["Project invistra", "#project-invistra"],
  ["Project inravina", "#project-inravina"],
  ["Project incless", "#project-incless"],
  ["Project iconoclast", "#project-iconoclast"],
  ["Project futhark", "#project-futhark"],
  ["Project extrinsicl", "#project-extrinsicl"],
  ["Project eclector", "#project-eclector"],
  ["Project ecclesia", "#project-ecclesia"],
  ["Project cyclosis", "#project-cyclosis"],
  ["Project ctype", "#project-ctype"],
  ["Project constrictor", "#project-constrictor"],
  ["Project consecution", "#project-consecution"],
  ["Project concrete-syntax-tree", "#project-concrete-syntax-tree"],
  ["Project common-macros", "#project-common-macros"],
  ["Project common-boot", "#project-common-boot"],
  ["Project clostrum", "#project-clostrum"],
  ["Project cleavir", "#project-cleavir"],
  ["Project buoy", "#project-buoy"],
  ["Project anatomicl", "#project-anatomicl"],
  ["Project acclimation", "#project-acclimation"],
  ["Overview", "#overview"]
  ];
